/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as DevelopmentsIndexRouteImport } from './routes/developments/index'
import { Route as DevelopmentsSlugRouteImport } from './routes/developments/$slug'
import { Route as GuideIndexRouteImport } from './routes/guide/index'
import { Route as GuideSlugRouteImport } from './routes/guide/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronUpdateRouteImport } from './routes/api/cron/update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsIndexRoute = DevelopmentsIndexRouteImport.update({
  id: '/developments/',
  path: '/developments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentsSlugRoute = DevelopmentsSlugRouteImport.update({
  id: '/developments/$slug',
  path: '/developments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/guide/$slug',
  path: '/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronUpdateRoute = ApiCronUpdateRouteImport.update({
  id: '/api/cron/update',
  path: '/api/cron/update',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/whats-new': typeof WhatsNewRoute
  '/developments/$slug': typeof DevelopmentsSlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/developments/': typeof DevelopmentsIndexRoute
  '/guide/': typeof GuideIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/update': typeof ApiCronUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/whats-new': typeof WhatsNewRoute
  '/developments/$slug': typeof DevelopmentsSlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/developments': typeof DevelopmentsIndexRoute
  '/guide': typeof GuideIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/update': typeof ApiCronUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/whats-new': typeof WhatsNewRoute
  '/developments/$slug': typeof DevelopmentsSlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/developments/': typeof DevelopmentsIndexRoute
  '/guide/': typeof GuideIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/update': typeof ApiCronUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/whats-new'
    | '/developments/$slug'
    | '/guide/$slug'
    | '/developments/'
    | '/guide/'
    | '/api/auth/$'
    | '/api/cron/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/whats-new'
    | '/developments/$slug'
    | '/guide/$slug'
    | '/developments'
    | '/guide'
    | '/api/auth/$'
    | '/api/cron/update'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/whats-new'
    | '/developments/$slug'
    | '/guide/$slug'
    | '/developments/'
    | '/guide/'
    | '/api/auth/$'
    | '/api/cron/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatsNewRoute: typeof WhatsNewRoute
  DevelopmentsSlugRoute: typeof DevelopmentsSlugRoute
  GuideSlugRoute: typeof GuideSlugRoute
  DevelopmentsIndexRoute: typeof DevelopmentsIndexRoute
  GuideIndexRoute: typeof GuideIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronUpdateRoute: typeof ApiCronUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments/': {
      id: '/developments/'
      path: '/developments'
      fullPath: '/developments/'
      preLoaderRoute: typeof DevelopmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developments/$slug': {
      id: '/developments/$slug'
      path: '/developments/$slug'
      fullPath: '/developments/$slug'
      preLoaderRoute: typeof DevelopmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/guide'
      fullPath: '/guide/'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/guide/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/update': {
      id: '/api/cron/update'
      path: '/api/cron/update'
      fullPath: '/api/cron/update'
      preLoaderRoute: typeof ApiCronUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatsNewRoute: WhatsNewRoute,
  DevelopmentsSlugRoute: DevelopmentsSlugRoute,
  GuideSlugRoute: GuideSlugRoute,
  DevelopmentsIndexRoute: DevelopmentsIndexRoute,
  GuideIndexRoute: GuideIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronUpdateRoute: ApiCronUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
